config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new"
  get 'logout', to: "sessions#destroy"
  get 'posts/new', to: "posts#new"

  post 'signup', to: "users#create"
  post 'login', to: "sessions#create"
  post 'posts/new', to: "posts#create"
  post '/posts/:post_id/comments/new', to: "comments#create"
  post '/comments/:comment_id/comments/new', to: "comments#create"

  resources :users
  resources :sessions
  resources :posts do 
    resources :comments
  end
  resources :comments do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :votable, polymorphic: true
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :votes, as: :votable

  validates :title,
  presence: true,
  length: {
    minimum: 10,
    maximum: 100,
    too_short: "must have at least %{count} words",
    too_long: "must have at most %{count} words"
  }

	validates :link, :url => true

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	has_many :ratings, class_name: 'Vote'

	validates :name,
	presence: true,
	length: {
    	minimum: 1,
    	maximum: 200,
    	too_short: "must have at least %{count} words",
    	too_long: "must have at most %{count} words"
  	}

	validates :email,
	presence: true,
	uniqueness: {case_sensitive: false},
	email: true

	validates_presence_of :password, on: :create
  	has_secure_password

  	def self.authenticate email, password
  		User.find_by_email(email).try(:authenticate, password)
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true
  belongs_to :commentable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated?
  	unless current_user
  		flash[:danger] = "Improper credentials."
  		redirect_to login_path
  	end
  end

  def current_user
  	@current_user ||= User.find_by_id(session[:user_id])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new # renders new comment form
	end

	def create # creates a new comment in db
		if (params[:post_id]) then
		@current_user.comments.create({:body => form_params['body'], :post_id => params[:post_id]})
		redirect_to root_path
		elsif (params[:comment_id]) then
		c = Comment.find params[:comment_id]
		@current_user.comments << c.comments.create({:body => form_params['body'], :user => @current_user})
		redirect_to root_path
		end
	end

	def destroy	 # deletes comment from db
	end

	private

	def form_params
   		params.require(:comment).permit(:body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :is_authenticated?, except: [:index]
	
	def index # shows a list of posts
		@posts = Post.all
		@margin = 0
	end

	def new # renders new post form
	end

	def create # creates a new post in db
		@current_user.post.create form_params
		redirect_to root_path
	end

	def destroy	
	end

	private

	def form_params
   		params.require(:post).permit(:title, :link)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :is_authenticated?, only: [:destroy]
	def create
		user = User.authenticate user_params['email'], user_params['password']

		if user
			session[:user_id] = user.id
			flash[:success] = "You are logged in."
			redirect_to root_path
		else
			flash[:danger] = "Improper credentials."
			redirect_to login_path
		end
	end

	def new
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have been logged out."
		redirect_to root_path

	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new # render the signup form
		
	end

	def create # creates a new user in db
		User.create signup_params
		redirect_to root_path
	end

	private

	def signup_params
   		params.require(:user).permit(:email, :password, :name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h2>Add comment:</h2>
<%= bootstrap_form_for :comment do |c| %>
	<%= c.text_field :body, placeholder: 'Enter comment' %>
	<%= c.primary 'Create' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Rails News</title>

		<!-- Bootstrap CSS -->
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>	
	</head>
	<body>
	<div class="container">
		<h1>Rails News</h1>
		<%= render "partials/flash" %>
		<%= yield %>
	</div>

		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% def get_comments array %>
	<% array.each do |comment| %>
		<% @margin += 10 %>
		<div style="margin-left: <%= @margin %>px"><small><%= comment.body %></small> | <%= link_to "Add Comment", new_comment_comment_path(comment.id) %></div>
	<% get_comments comment.comments %>
	<% end %>
<% end %>

<% if @current_user %>
<%= link_to "Log out", logout_path, class: 'btn btn-default' %>
<% else %>
<%= link_to "Log in", login_path, class: 'btn btn-default' %>
<% end %>
<%= link_to "Add post", new_post_path, class: 'btn btn-default' %>
<ol>
<% @posts.each do |post| %>
<li>
<a href="<%= post.link %>"><%= post.title %></a> | 
<%= link_to "Add Comment", new_post_comment_path(post.id) %><br>

<% get_comments post.comments %>

</li>
<% end %>
</ol>

app/views/posts/new.html.erb
<h2>Add post</h2>
<%= form_for :post do |f| %>
	<%= f.text_field :title, placeholder: 'Enter a title for this post' %>
	<%= f.text_field :link, placeholder: 'Enter a valid link' %>
	<%= f.submit 'Create' %>
<% end %>

app/views/users/new.html.erb
signup form

<%= form_for :user do |f| %>
	<%= f.text_field :name, placeholder: 'Enter your name' %>
	<%= f.email_field :email, placeholder: 'Enter your email' %>
	<%= f.password_field :password, placeholder: 'Enter your password' %>
	<%= f.submit 'Sign up' %>
<% end %>